name: Build and Test

on:
  push:
    branches: ["*"]
    paths-ignore:
      - "*.md"
  pull_request:
    branches: [master, dev]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
        python-version: ["3.10"]
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: 'requirements-dev.txt'
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: pandoc
          version: 1.0
      - name: Install package and dependencies
        run: |
          pip install -r requirements-dev.txt
      - name: Test with pytest
        run: |
          pytest -v -x tests/
